config/routes.rb
Gadgetapp::Application.routes.draw do
  devise_for :users

  

  
  root to: "gadgets#index"

  resources :gadgets

end

app/models/gadget.rb
class Gadget < ActiveRecord::Base
	has_many :images, :dependent => :destroy
	belongs_to :user

end

app/models/image.rb
class Image < ActiveRecord::Base
	belongs_to :gadget

	has_attached_file :photo, :styles => {:small => '30x30#', :large => '100x100#'}, :default_url => '/images/:id/photo_:style.png'

  do_not_validate_attachment_file_type :photo

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :gadgets
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/gadgets_controller.rb
class GadgetsController < ApplicationController
	before_action :authenticate_user!
	before_action :set_gadget, only: [:edit, :update, :destroy]



	def index
		if params[:q]
			@search_string = params[:q]
			@query_string = @search_string.gsub(/[^0-9a-z ]/i, '')
			logger.info "@query_string: " + @query_string
			@gadgets = Gadget.find_by_sql("select * from gadgets where (name like '%#{@query_string}%' or manufacturer like '%#{@query_string}%') and user_id = #{current_user.id} order by created_at DESC")
		else
			@gadgets = Gadget.where("user_id" => current_user.id)
			@images = Image.find_by_sql("select * from gadgets g, images i where i.gadget_id = g.id and g.user_id = #{current_user.id}")
		end
	end

	def new
		@gadget = Gadget.new
	end

	def edit
	end

	def create
		@gadget = Gadget.new(gadget_params)

	  if @gadget.save
	  	@gadget.user_id = current_user.id
	  	@gadget.save
	  	if params[:images]
        params[:images].each { |image|
          @gadget.images.create(photo: image)
        }
      end
	    redirect_to gadgets_url, notice: 'Gadget was successfully created.'
	  else
	    render action: 'new', notice: 'Gadget was not created.'
	  end
	end

	def update
		respond_to do |format|
      if @gadget.update(gadget_params)
        format.html { redirect_to gadgets_url, notice: 'Gadget was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
	end

	def destroy
		@gadget.destroy
    redirect_to gadgets_url
	end

  private
    def set_gadget
      @gadget = Gadget.find(params[:id])
    end

    def gadget_params
      params.require(:gadget).permit(:name, :manufacturer, :retired)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gadgets_helper.rb
module GadgetsHelper
end

app/views/gadgets/_carousel.html.erb
<div id="slider">
  <div class="slick-carousel">
    <% @images.each do |i| %>
      <div>
        <a>
        <% if @images.count < 6 %>
          <img src="<%= root_url + "system/images/photos/000/000/0" + i.id.to_s + "/large/" + i.photo_file_name %>" />
        <% else %>
          <img data-lazy="<%= root_url + "system/images/photos/000/000/0" + i.id.to_s + "/large/" + i.photo_file_name %>" />
        <% end %>
        </a>
      </div>
    <% end %>
  </div>
</div>

<script>
  $('.slick-carousel').slick({
    lazyLoad: 'ondemand',
    slidesToShow: 6,
    slidesToScroll: 6,
    infinite: true
  });
</script>

app/views/gadgets/_form.html.erb
<%= form_for @gadget, :html => {:multipart => true} do |f| %>

    <%= f.label :name %>
    <%= f.text_field :name, :class => "form-control" %>

    <%= f.label :manufacturer %>
    <%= f.text_field :manufacturer, :class => "form-control" %>

    <%= f.label :retired %>
    <%= f.check_box :retired %><br />
    
    <%= f.label :images %>
    <%= file_field_tag "images[]", type: :file, multiple: true, :class => "form-control" %>

    <button type="submit" class="btn btn-primary">Submit</button>
<% end %>

app/views/gadgets/edit.html.erb
<div class="container">
	<h1>Edit Gadget</h1>

	<%= render 'form' %>

	<%= link_to 'Back', gadgets_path %>
</div>

app/views/gadgets/index.html.erb
<div class="container">
	<% if !@gadgets.blank? %>
		<% unless params[:q] %>
			<%= render "carousel" %>
		<% end %>

	  <table class="table table-striped">
	    <thead>
	      <tr>
	      	<th>Image</th>
	        <th>Name</th>
	        <th>Manufacturer</th>
	        <th>Retired</th>
	        <th></th>
	        <th></th>
	      </tr>
	    </thead>
	    <tbody>
				<% @gadgets.each do |g| %>
					<tr>  
						<td>    
							<% if g.images[0] %>    
								<img src="<%= root_url + "system/images/photos/000/000/0" + g.images[0].id.to_s + "/small/" +  g.images[0].photo_file_name %>"/> 
							<% end %>
						</td>
						<td><%= g.name %></td>
						<td><%= g.manufacturer %></td>
						<td><%= g.retired %></td>
						<td><%= link_to 'Edit', edit_gadget_path(g) %></td>
          	<td><%= link_to 'Delete', g, method: :delete, data: { confirm: 'Are you sure?' } %></td>
					</tr>
				<% end %>
			</tbody>
		</table>
	<% else %>
		You don't have any gadgets! What a shame.
	<% end %>
</div>

app/views/gadgets/new.html.erb
<div class="container">
	<h1>New Gadget</h1>

	<%= render 'form' %>

	<%= link_to 'Back', gadgets_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

  <title>My Gadgets</title>
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "bootstrap.min" %>
  <%= javascript_include_tag "slick.min.js" %>
  <%= csrf_meta_tags %>
</head>
<nav class="navbar navbar-default" role="navigation">
<div class="container-fluid">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%= link_to "My Gadgets", gadgets_url, :class => "navbar-brand" %>
  </div>
  <div id="navbar" class="navbar-collapse collapse">
    <ul class="nav navbar-nav">
      <li><%= link_to "Add Gadget", new_gadget_path %></li>  
    </ul>
    <% if user_signed_in? %>
      <%= form_tag(url_for(:action => "index", :controller => "gadgets"), :method => :get) do %>
        <%= text_field_tag :q, params[:q] %>
        <button type="submit" class="btn btn-primary">Search</button>
      <% end %>
			<ul class="nav navbar-nav navbar-right">
			  <li class="current_user">Welcome <%= current_user.email%>! </li>
		      <li><%= link_to("Log Out", destroy_user_session_path, :method => :delete)  %></li>
			</ul>
		<% end %>
  </div><!--/.nav-collapse -->
</div><!--/.container-fluid -->
</nav>

<body>
  <% flash.each do |name, msg| -%>
    <div class="alert alert-warning">
      <%= content_tag :div, msg, class: name %>
    </div>
  <% end -%>

<%= yield %>

</body>
</html>